### ISSUE TITLE
 ReferenceError: primordials is not defined

### ISSUE THREAD

**Issue by KiroFyzu** [MilllerTime/menja#15]
PS D:\belajar-python\mini-game\menja> npm run build

> menja@0.1.0 build
> gulp

fs.js:47
} = primordials;
    ^

ReferenceError: primordials is not defined
    at fs.js:47:5
    at req_ (D:\belajar-python\mini-game\menja\node_modules\natives\index.js:143:24)
    at Object.req [as require] (D:\belajar-python\mini-game\menja\node_modules\natives\index.js:55:10)
    at Object.<anonymous> (D:\belajar-python\mini-game\menja\node_modules\vinyl-fs\node_modules\graceful-fs\fs.js:1:37)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)

**Comment by KiroFyzu** [comment]
me using npm | node.js

**Comment by ArcticFox520** [comment]
I also encountered this problem. I used yarn, and I tried nodejs16 and nodejs18.

The following is the error log

[00:38:28.924] yarn run v1.22.19
[00:38:28.972] $ gulp
[00:38:29.962] fs.js:42
[00:38:29.962] } = primordials;
[00:38:29.962]     ^
[00:38:29.963] 
[00:38:29.963] ReferenceError: primordials is not defined
[00:38:29.963]     at fs.js:42:5
[00:38:29.965]     at req_ (/vercel/path0/node_modules/natives/index.js:143:24)
[00:38:29.965]     at Object.req [as require] (/vercel/path0/node_modules/natives/index.js:55:10)
[00:38:29.965]     at Object.<anonymous> (/vercel/path0/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:37)
[00:38:29.965]     at Module._compile (node:internal/modules/cjs/loader:1198:14)
[00:38:29.965]     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
[00:38:29.965]     at Module.load (node:internal/modules/cjs/loader:1076:32)
[00:38:29.965]     at Function.Module._load (node:internal/modules/cjs/loader:911:12)
[00:38:29.965]     at Module.require (node:internal/modules/cjs/loader:1100:19)
[00:38:29.965]     at require (node:internal/modules/cjs/helpers:119:18)
[00:38:29.978] error Command failed with exit code 1.
[00:38:29.978] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by MilllerTime** [comment]
Yes the project had old tooling that seems to have broken on modern Node.

I've applied a minimal fix, upgrading gulp and browser-sync. This now works with Yarn on Node 22.
